spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    cache: false
    template-resolver-order: 0
    check-template-location: true
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/, classpath:/images/

logging:
  level:
    com.callor.hello: debug